---
swagger: '2.0'
info:
    description: Shopping Api with Express & Sequelize
    version: '1.0'
    title: Nodejs Shop API
    contact:
        email: yassersharifi74@gmail.com
externalDocs:
    description: Read about the developer
    url: http://127.0.0.1:3000/docs
host: 127.0.0.1:3000
schemes:
    - http
    - https
securityDefinitions:
    Bearer:  
        in: header  
        type: apiKey  
        name: Authorization 
        description: "Enter the token with the Bearer: prefix, e.g. 'Bearer abcde12345'"
tags:
    - name: user
      description: Operations about user
